import { baseConfig } from "@workspace/eslint-config/base"
import { defineConfig, globalIgnores } from "eslint/config"

export default defineConfig([
  ...baseConfig,
  // Generated by `wrangler types`; not ours to lint.
  globalIgnores(["worker-configuration.d.ts"]),
])
