// AUTO-GENERATED — run `bun scripts/generate-skill-icons.mjs` to refresh.
// Edit the OVERRIDES table in that script, not this file.
//
// 148 of 222 skills have a brand mark, drawn from 113 distinct icons.
// The other 74 are concepts rather than products ("Caching", "Error Boundaries") or brands
// simple-icons no longer ships, and render as an initials tile — the design's intended fallback.

import {
  siAngular,
  siAntdesign,
  siAnthropic,
  siApollographql,
  siAppwrite,
  siAstro,
  siBetterauth,
  siBiome,
  siChakraui,
  siClaude,
  siClerk,
  siCloudflareworkers,
  siCockroachlabs,
  siCypress,
  siD3,
  siDatefns,
  siDocker,
  siDocusaurus,
  siDrizzle,
  siElasticsearch,
  siElectron,
  siElevenlabs,
  siExpo,
  siExpress,
  siFastify,
  siFirebase,
  siFramer,
  siGit,
  siGithubactions,
  siGooglegemini,
  siGraphql,
  siHeadlessui,
  siHono,
  siHuggingface,
  siKubernetes,
  siLangchain,
  siLeaflet,
  siMantine,
  siMapbox,
  siMeilisearch,
  siMistralai,
  siMobx,
  siMockserviceworker,
  siModal,
  siMongodb,
  siMongoose,
  siMui,
  siMysql,
  siNeon,
  siNestjs,
  siNetlify,
  siNextdotjs,
  siNuxt,
  siNx,
  siOclif,
  siOllama,
  siOpenapiinitiative,
  siPayloadcms,
  siPinia,
  siPlanetscale,
  siPnpm,
  siPostgresql,
  siPosthog,
  siPrettier,
  siPrisma,
  siPulumi,
  siQdrant,
  siQwik,
  siRadixui,
  siReact,
  siReacthookform,
  siReactivex,
  siReactquery,
  siReactrouter,
  siRedis,
  siRedux,
  siRemix,
  siReplicate,
  siResend,
  siSanity,
  siSentry,
  siSequelize,
  siShadcnui,
  siSocketdotio,
  siSolid,
  siSst,
  siStorybook,
  siStrapi,
  siStripe,
  siSupabase,
  siSurrealdb,
  siSvelte,
  siSwr,
  siTailwindcss,
  siTanstack,
  siTauri,
  siTerraform,
  siTestinglibrary,
  siThreedotjs,
  siTrpc,
  siTurborepo,
  siTurso,
  siTypeorm,
  siTypescript,
  siUpstash,
  siVercel,
  siVite,
  siVitepress,
  siVitest,
  siVuedotjs,
  siVuetify,
  siVueuse,
  siZod,
} from "simple-icons"

/** Skill slug → SVG path data, for a 24×24 viewBox. */
export const SKILL_ICON_PATHS: Record<string, string> = {
  "angular-standalone": siAngular.path,
  "ant-design": siAntdesign.path,
  "anthropic-sdk": siAnthropic.path,
  "apollo-server": siApollographql.path,
  appwrite: siAppwrite.path,
  astro: siAstro.path,
  "axiom-pino-sentry": siSentry.path,
  "better-auth-drizzle-hono": siBetterauth.path,
  biome: siBiome.path,
  "chakra-ui": siChakraui.path,
  "claude-vision": siClaude.path,
  clerk: siClerk.path,
  "cloudflare-workers": siCloudflareworkers.path,
  cockroachdb: siCockroachlabs.path,
  "cypress-e2e": siCypress.path,
  d3: siD3.path,
  "date-fns": siDatefns.path,
  docker: siDocker.path,
  docusaurus: siDocusaurus.path,
  drizzle: siDrizzle.path,
  eas: siExpo.path,
  elasticsearch: siElasticsearch.path,
  electron: siElectron.path,
  "electron-forge": siElectron.path,
  "electron-ipc": siElectron.path,
  "electron-multiwindow": siElectron.path,
  "electron-security": siElectron.path,
  "electron-storage": siElectron.path,
  "electron-testing": siElectron.path,
  "electron-ui": siElectron.path,
  "electron-updater": siElectron.path,
  elevenlabs: siElevenlabs.path,
  "eslint-prettier": siPrettier.path,
  expo: siExpo.path,
  "expo-router": siExpo.path,
  express: siExpress.path,
  "expressive-typescript": siTypescript.path,
  fastify: siFastify.path,
  firebase: siFirebase.path,
  "framer-motion": siFramer.path,
  "git-hooks": siGit.path,
  "github-actions": siGithubactions.path,
  "google-gemini-sdk": siGooglegemini.path,
  "graphql-apollo": siApollographql.path,
  "headless-ui": siHeadlessui.path,
  hono: siHono.path,
  "huggingface-inference": siHuggingface.path,
  kubernetes: siKubernetes.path,
  langchain: siLangchain.path,
  leaflet: siLeaflet.path,
  mantine: siMantine.path,
  mapbox: siMapbox.path,
  meilisearch: siMeilisearch.path,
  "mistral-sdk": siMistralai.path,
  mobx: siMobx.path,
  modal: siModal.path,
  mongodb: siMongodb.path,
  mongoose: siMongoose.path,
  msw: siMockserviceworker.path,
  mui: siMui.path,
  mysql: siMysql.path,
  nativewind: siTailwindcss.path,
  neon: siNeon.path,
  nestjs: siNestjs.path,
  netlify: siNetlify.path,
  nextjs: siNextdotjs.path,
  nuxt: siNuxt.path,
  nx: siNx.path,
  "oclif-ink": siOclif.path,
  ollama: siOllama.path,
  openapi: siOpenapiinitiative.path,
  payload: siPayloadcms.path,
  pinia: siPinia.path,
  planetscale: siPlanetscale.path,
  "pnpm-workspaces": siPnpm.path,
  postgresql: siPostgresql.path,
  "posthog-analytics": siPosthog.path,
  "posthog-flags": siPosthog.path,
  prisma: siPrisma.path,
  pulumi: siPulumi.path,
  qdrant: siQdrant.path,
  qwik: siQwik.path,
  "radix-ui": siRadixui.path,
  react: siReact.path,
  "react-hook-form": siReacthookform.path,
  "react-native": siReact.path,
  "react-native-security": siReact.path,
  "react-navigation": siReact.path,
  "react-query": siReactquery.path,
  "react-router": siReactrouter.path,
  "react-testing-library": siTestinglibrary.path,
  "react-three-fiber": siThreedotjs.path,
  redis: siRedis.path,
  "redux-toolkit": siRedux.path,
  remix: siRemix.path,
  replicate: siReplicate.path,
  "resend-react-email": siResend.path,
  rxjs: siReactivex.path,
  sanity: siSanity.path,
  sequelize: siSequelize.path,
  "setup-axiom-pino-sentry": siSentry.path,
  "setup-posthog": siPosthog.path,
  "setup-resend": siResend.path,
  "shadcn-ui": siShadcnui.path,
  "socket-io": siSocketdotio.path,
  solidjs: siSolid.path,
  sst: siSst.path,
  storybook: siStorybook.path,
  strapi: siStrapi.path,
  stripe: siStripe.path,
  supabase: siSupabase.path,
  surrealdb: siSurrealdb.path,
  svelte: siSvelte.path,
  sveltekit: siSvelte.path,
  swr: siSwr.path,
  tailwind: siTailwindcss.path,
  "tanstack-form": siTanstack.path,
  "tanstack-router": siTanstack.path,
  "tanstack-table": siTanstack.path,
  tauri: siTauri.path,
  "tauri-backend": siTauri.path,
  "tauri-bundling": siTauri.path,
  "tauri-mobile": siTauri.path,
  "tauri-multiwindow": siTauri.path,
  "tauri-plugins": siTauri.path,
  "tauri-security": siTauri.path,
  terraform: siTerraform.path,
  trpc: siTrpc.path,
  turborepo: siTurborepo.path,
  "turborepo-ci": siTurborepo.path,
  turso: siTurso.path,
  typeorm: siTypeorm.path,
  "typescript-config": siTypescript.path,
  upstash: siUpstash.path,
  vercel: siVercel.path,
  "vercel-ai-sdk": siVercel.path,
  "vercel-kv": siVercel.path,
  "vercel-postgres": siVercel.path,
  vite: siVite.path,
  vitepress: siVitepress.path,
  vitest: siVitest.path,
  "vue-composition-api": siVuedotjs.path,
  "vue-i18n": siVuedotjs.path,
  "vue-test-utils": siVuedotjs.path,
  vuetify: siVuetify.path,
  vueuse: siVueuse.path,
  yoga: siGraphql.path,
  "zod-validation": siZod.path,
}
